# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec6e0fa56a544d70c1d074d19d9b931e464784ddb7ac14cd90ef070a59b2ac4dab74c354fc8427168e81f479823fcae84742034e0fe9deb024f42b5399454b4f

test:
  secret_key_base: ddc8dd06e91b6c7ce3486771310af41480b80e5ece21be829dc3338bfe8c7c6e1ed29ca194cf2d24d4de21867b59b8af9ee8627690498fe6f49bea542d98f4c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
